POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbW8yQGRlbW8uY29tIiwiZXhwIjoxNzQzOTQ2NDU5LCJ1c2VySWQiOjB9.gQyEnw50Lq6LmRIaUEopHx1YsxegNBlXlZxK8eiDPOw

{
    "name": "fourth test event",
    "description": "my fourth test event post request using gin",
    "location": "nuremberg DE",
    "datetime": "2025-04-06T16:00:03.000Z"
}