DELETE http://localhost:8080/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbW9AZ21haWwuY29tIiwiZXhwIjoxNzQzOTQ4Nzc2LCJ1c2VySWQiOjB9._SgQpduxBGRFsBT9gdMxk8NP1hjp8GJYKYhidJuzLqY